[tool.poetry]
name = "HW02"
version = "0.0.1"
description = "Hw02"
authors = ["Vladislav Nosivskoy"]

[tool.poetry.dependencies]
python = "^3.9"
prettyAst = "^0.0.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"